### ISSUE TITLE
`@session` with `tags=...` doesn't typecheck

### ISSUE THREAD

**Issue by dbohdan** [cjolowicz/nox-poetry#1219]
The `session` decorator now takes an [optional `tags` argument](https://nox.thea.codes/en/stable/config.html#defining-sessions). Please update the types to reflect this.

**Comment by mariuswinger** [comment]
Unless there are some pitfalls I am unaware of, this should just amount to adding "tags: Sequence[str] = ...," to 'sessions.pyi'.
