### ISSUE TITLE
Issue specifying `DistributionFormat` to install

### ISSUE THREAD

**Issue by mLewisLogic** [cjolowicz/nox-poetry#127]
👋 Just started playing with the lib. Love the concept.

I tried running the following:
```py
import nox
import nox_poetry.patch  # noqa
from nox.sessions import Session
from nox_poetry.poetry import DistributionFormat

@nox.session(python=["3.8"])
def test(session: Session) -> None:
    session.install(".", DistributionFormat.SDIST)
    session.run("pytest")
```

Oddly enough it executed both `poetry build --format=wheel` and `poetry build --format=sdist`.

It then tried to run its uninstall stage for both distribution types and blew up on the sdist step.

```
nox > pip uninstall --yes file:///Users/mike/code/bookie/submodules/nautilus_trader/dist/nautilus_trader-1.75.0-cp38-cp38-macosx_10_15_x86_64.whl#sha256=fa0c39cd79a49f01b31692aeacb1b87900cd754de0019f9f2b50bb826dd041ed
nox > pip uninstall --yes file:///Users/mike/code/bookie/submodules/nautilus_trader/dist/nautilus_trader-1.75.0.tar.gz#sha256=c5d6037013386b75cd459ab417e3dd6cb4f0846d155839055663a376b7c90de1
nox > Command pip uninstall --yes file:///Users/mike/code/bookie/submodules/nautilus_trader/dist/nautilus_trader-1.75.0.tar.gz#sha256=c5d6037013386b75cd459ab417e3dd6cb4f0846d155839055663a376b7c90de1 failed with exit code 1:
```

Is this a bug, or am I using the tool incorrectly?

**Comment by cjolowicz** [comment]
Thanks for the feedback! Maybe the documentation could be improved here. This package is still in early development.

When importing `nox_poetry.patch`, you use `session.install(".")` to build the package. This will always build a wheel. The positional arguments of this function are all strings; it is not possible to pass `SDIST` or `WHEEL`.

If you need more control, and want to build an sdist, you should use the "explicit" interface `nox_poetry.install(session, nox_poetry.SDIST)` instead. Do not pass `"."` in this case. If you only use the explicit interface, then you don't need to import `nox_poetry.patch`; just import `nox_poetry`.

Also note that the public API has `nox_poetry.SDIST` and `nox_poetry.WHEEL`. You don't need to use `nox_poetry.poetry.DistributionFormat.SDIST`, and probably shouldn't as it's an implementation detail.

**Comment by cjolowicz** [comment]
The `pip uninstall` step should not fail. So there's probably also a bug here 🤔

**Comment by mLewisLogic** [comment]
Ah, thanks for the explanation. Will give that a shot soon.

Ya, the sdist is actually a bit of a shim.
It's for a large Cython repo. I'd like to produce two different compiled "versions", a speed-optimized version and a debug/tracing version. Poetry itself doesn't support configuration of something like that beyond the `pyproject.toml`.
I can flip flags in the build script via ENV params, but regardless of them, the wheel filenames will be identical (and so different "versions" will collide). That's the nut of the problem.
Different nox session targets should run on builds compiled with different flags, so doing the actual build/compilation within each session's venv seems like the safest route.

If you have any other setup suggestion you think could work or features you'd like me to guinea pig I'd be happy to try it out and report back on results.

**Comment by mLewisLogic** [comment]
K, `session.install` vs `nox_poetry.install` was the issue that was causing both wheels and sdist to build.

I think I figured out the issue with the sdist uninstall.

Pretty sure that there needs to be an `&egg=package-name` appended to the return path in `core.build_package`.

Pip callchain:
* https://github.com/pypa/pip/blob/dcc12f3786d92f95bfe08558d32dc3bc575c88ce/src/pip/_internal/commands/uninstall.py#L62-L64
* https://github.com/pypa/pip/blob/dcc12f3786d92f95bfe08558d32dc3bc575c88ce/src/pip/_internal/req/constructors.py#L408
* https://github.com/pypa/pip/blob/dcc12f3786d92f95bfe08558d32dc3bc575c88ce/src/pip/_internal/req/constructors.py#L342
* https://github.com/pypa/pip/blob/dcc12f3786d92f95bfe08558d32dc3bc575c88ce/src/pip/_internal/models/link.py#L162


So, seems like we'd want the user to pass in an egg name (though I guess we _could_ try to extract it from the `.tar.gz` file, but that seems excessive). Might change the calling semantics of `nox_poetry.install`. Perhaps if an `SDIST` `DistributionFormat` is passed then there must be exactly one arg (the name of the egg)?
Maybe it's different enough to warrant it's own `.install_sdist("package-name")` method?
On the other hand, since it is a self build, maybe all of that is skipped and you just hack it with a static placeholder like `&egg=nox-poetry-local-build`.

Lots of ugly viable solutions!

**Comment by mLewisLogic** [comment]
Should I spin this out as a separate issue (since the issue is identified and specific)? Or is this issue good enough for tracking?

**Comment by cjolowicz** [comment]
Thanks for providing additional details! I'll probably take a closer look this week.

**Comment by mLewisLogic** [comment]
Also, since you're specifying install sources by sha256, you could probably skip the uninstall step (and maybe even the install step) if the shas match?

**Comment by cjolowicz** [comment]
This took a while longer, unfortunately... You analysis was spot on. No need to have the user pass the egg name, it's just the name of the local package, which we can get from Poetry. Do let me know if sdists are still a problem, and thanks again for the report and analysis.

> Also, since you're specifying install sources by sha256, you could probably skip the uninstall step (and maybe even the install step) if the shas match?

I don't think that would work. We'd need the sha256 of the package that was previously installed, and we don't have that anymore.
