### ISSUE TITLE
Specifying extras when installing the project package

### ISSUE THREAD

**Issue by alexifm** [cjolowicz/nox-poetry#146]
It doesn't look like this is possible but let me know if it is:

```
# noxfile.py
import nox
import nox_poetry.patch
from nox.sessions import Session

@nox.session
def tests(session: Session) -> None:
    """Run the test suite."""
    session.install(".[extra]")
    session.install("pytest")
    session.run("pytest")
```

I think the logic would need to be handled to detect the leading `.` and then take the eventual wheel path and add on the suffix `[extra]`.

**Comment by cjolowicz** [comment]
Thank you for reporting this :+1: 

This was fixed in #181

**Comment by epenet** [comment]
Is there a workaround until the next release is available?

**Comment by cjolowicz** [comment]
@epenet This has been released in [0.6.0] :burrito: 

[0.6.0] https://github.com/cjolowicz/nox-poetry/releases/0.6.0

**Comment by alexifm** [comment]
Thanks @cjolowicz!

**Comment by epenet** [comment]
Thanks @cjolowicz !
