### ISSUE TITLE
Using mypy (or pytype) Causes Issue Regarding --require-hashes

### ISSUE THREAD

**Issue by jeffnyman** [cjolowicz/nox-poetry#196]
I realize this is questionable in terms of what tooling is actually generating the problem here. The reason it seems to be the case here is because the generated `requirements.txt` file is what complains about unpinned versions. And `nox-poetry` seems to be generating that file. If I don't use `nox-poetry`, I can get this to work.

I should also note that I have only tested this so far on a MacOS.

I have `mypy` as part of my project and I used this as part of the nox file:

```
import nox
import nox_poetry.patch

locations = "src", "tests", "noxfile.py"

@nox.session(python="3.7")
def typing(session):
    """Run the type checker (using mypy)."""

    args = session.posargs or locations
    session.install("mypy")
    session.run("mypy", *args)
```

When I run `nox -s typing`, that returns a slew of errors where the important bit seems to be:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==.
These do not:
    typed-ast<1.5.0,>=1.4.0
(from mypy==0.790)
```

After reading a few things, I tried to do this:

```
@nox.session(python="3.8")
def typing(session):
    """Run the type checker (using mypy)."""

    args = session.posargs or ["--without-hashes", locations]
    session.install("mypy")
    session.run("mypy", *args)
```

Note the addition of the `--without-hashes` but that doesn't seem to have any impact. I get the same error.

I saw there was a mypy entry in this repository, so I changed mine to match it:

```
@nox.session(python="3.8")
def typing(session):
    """Run the type checker (using mypy)."""

    args = session.posargs or locations
    session.install(".")
    session.install("mypy")
    session.run("mypy", *args)
    if not session.posargs:
        session.run("mypy", f"--python-executable={sys.executable}", "noxfile.py")
```

That similarly has no impact. I get the exact same error.

I can run the following and I get no errors at all:

```
 poetry run mypy src
```

With that mypy does actually run and indicates which files did or did not have typing issues. However, trying to do that in the above does not work. For example, if I do this:

```
session.run("poetry", "run", "mypy", *args)
```

I get the same issue regarding the "--require-hashes" error.

It looks like the issue is with anything that uses `typed-ast`. Originally I tried this only with mypy but I also tried with pytype and get the same error.

**Comment by epenet** [comment]
Looks like the `--without-hashes` needs to be injected here: https://github.com/cjolowicz/nox-poetry/blob/master/src/nox_poetry/poetry.py#L70

Is this linked to new pip dependency resolver?
https://github.com/cjolowicz/hypermodern-python/issues/174

Probably also linked to CI failures on #192

**Comment by epenet** [comment]
@cjolowicz what do you think of PR #222 ?
