### ISSUE TITLE
Patched Nox Session Not Reading Some pyproject.toml Settings

### ISSUE THREAD

**Issue by jeffnyman** [cjolowicz/nox-poetry#243]
I'm finding that settings in the `pyproject.toml` are not read if I use the `nox-poetry` "patch" approach. I say "settings" but, in fact, I can only speak to this for one particular example, which I'll try to cover here. This issue might be very specific to just one setting, but I'm keeping the title of the issue generic for now.

Consider the following that I have in my pyproject.toml:

```
[tool.coverage.run]
source = ["quendor"]
omit = ["src/quendor/__main__.py"]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = ["def main()"]
```

Notice that I have specific omission of the file. I also ask to show branches and show missing. I'm also excluding a specific method. Thus when I run `poetry run pytest --cov`, the `__main__.py` is correctly excluded.

```
Name                         Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------
src/quendor/__init__.py          2      0      0      0   100%
src/quendor/__version__.py       1      0      0      0   100%
src/quendor/cli.py               9      0      0      0   100%
```

Notice that my `__main__.py` is (correctly) not showing up on the list. This also works correctly with the following Nox session (which is not using the `nox-poetry` approach):

```
@nox.session(python=["3.7", "3.8", "3.9"])
def tests(session) -> Session:
  args = session.posargs or ["--cov"]
  session.run("poetry", "install", external=True)
  session.run("pytest", *args)
```

However, when I use `nox-poetry` the `pyproject.toml` file is apparently not being read for the above setting. I say that because I change the above Nox session to this:

```
@nox.session(python=["3.7", "3.8", "3.9"])
def tests(session) -> Session:
  session.install(".")
    session.install("pytest")
    session.install("pytest-cov")
    session.install("coverage[toml]")
    session.install("expects")
   session.run("pytest", *args)
```

Notice that I do include the "[toml]" qualifier to the inclusion of the `coverage` tool. When I run this version, what I see is the following:

```
Name                         Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------
src/quendor/__init__.py          2      0      0      0   100%
src/quendor/__main__.py          8      8      4      0     0%   3-18
src/quendor/__version__.py       1      0      0      0   100%
src/quendor/cli.py               9      0      0      0   100%
```

Notice how `__main__.py` is appearing here, which implies that the `omit` setting from the `pyproject.toml` is not being referenced at all with this execution. Yet notice that it is still showing the Branch and Missing sections and it appears to be respecting the `exclude_lines` setting, which certainly seems to show that some (most) elements of the `pyproject.toml` file were read.

So at least for the purposes of this particular issue, it looks like only the `omit` is not being referenced. If that's the case, my title could be reflected to say that.

What I don't know is if this particular issue points the way to other possible issues.

**Comment by jeffnyman** [comment]
Update: If I move the `omit` setting to the "tool.coverage.report" section, everything works fine. Specifically, I change my `pyproject.toml` to look like this:

```
[tool.coverage.run]
source = ["quendor"]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = ["def main()"]
omit = ["src/quendor/__main__.py"]
```

Basically I moved the `omit` from "run" to "report". That then works when using the `nox-poetry` patch approach.

So maybe this issue is a non-issue. That said, the contents of my original report are still interesting in that running Pytest manually or with Nox (without nox-poetry) worked and respected `omit` in the "run" section, whereas the `nox-poetry` execution did not.

So that discrepancy is (maybe?) worth noting.

**Comment by cjolowicz** [comment]
Thanks for the report!

I believe this is not a nox-poetry issue, but a question of configuring Coverage.py to measure code coverage for an installed package. Let me explain.

When you install your package with Poetry (with or without Nox), your tests run against your source tree, because Poetry performs an editable install. Paths look exactly like the one you specified in your `omit` directive. By contrast, nox-poetry installs your package with pip (after building it with Poetry). This means that tests run against the installed package, and paths in the coverage data look like this: `.nox/tests-3-9/lib/python3.9/site-packages/quendor/...`. You need to tell Coverage.py how to map these paths back to your source tree:

```toml
[tool.coverage.paths]
source = ["src", "*/site-packages"]
```

Hopefully, Coverage.py will then also be able to correctly exclude the files in the `omit` directive.

**Comment by jeffnyman** [comment]
Got it. This makes sense. I have confirmed what you are describing above. Thank you for the response. I'll close this out.
