### ISSUE TITLE
mypy doesn't detect @session typing

### ISSUE THREAD

**Issue by matteosantama** [cjolowicz/nox-poetry#269]
This could be a bad configuration on my part, or even a mypy issue, but it seems that the `session` decorator is incorrectly typed.

I have the following session

```python
@session(python=package.base_python, venv_params=["--pip", package.pip_version])
def black(_session: Session) -> None:
    """Format with black."""
    args = _session.posargs or ["--check"] + package.locations
    _session.install("black")
    _session.run("black", *args)
```

And when I type-check it under mypy's "strict" ruleset, I get the following error

```
noxfile.py:93:2: error: Untyped decorator makes function "black" untyped  [misc]
    @session(python=package.base_python, venv_params=["--pip", package.pip_version])
```

As far as I can tell, the library is rather well typed so I'm not sure where the disconnect is.

**Comment by cjolowicz** [comment]
Thanks for the report :+1:

We do provide types for the session decorator. But maybe mypy is not able to locate them.

I can reproduce your error if I install nox in a virtualenv, and run mypy without activating that virtualenv.

If you do not want to install mypy into the same virtualenv, you can try the following command instead:

```sh
mypy --python-executable=path/to/venv/bin/python --strict noxfile.py
```

Here, you need to specify the full path to the Python interpreter used by Nox.

If you invoke mypy from the noxfile itself, you can simply use `sys.executable` here. That's what this project does in its own noxfile.

**Comment by matteosantama** [comment]
Thanks for the speedy response! I think the issue was that I was reusing virtual envs, so I had to clean out the cache.
