### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by danieleades** [cjolowicz/nox-poetry#286]
@cjolowicz I've fallen at the first hurdle!

```
pipx install nox
pipx inject nox nox-poetry
```

```python
from nox_poetry import session
```

```
Traceback (most recent call last):
  File "/home/dan/Code/python/nox-poetry-test/nox.py", line 1, in <module>
    from nox_poetry import session
ModuleNotFoundError: No module named 'nox_poetry'
```

`nox-poetry` is installed at `~/.local/pipx/venvs/nox/lib/python3.8/site-packages/nox_poetry`, but isn't being picked up by the interpreter. any additional steps i'm missing?

i'm probably missing something obvious, i don't usually use pipx

**edit:** I'm guessing I'll need to install `nox-poetry` in both the `nox` virtualenv *and* on the system right? In the former so that `nox` picks it up, and the latter so my IDE picks it up. And then keep them manually aligned. Is that correct?

Hmm I've also found if i install both using pip I get a circular import

```
pip install --user nox
pip install --user nox-poetry
```
```python
from nox_poetry import session
```
```
ImportError: cannot import name 'session' from partially initialized module 'nox_poetry' (most likely due to a circular import)
```

**Comment by danieleades** [comment]
this is an interesting one.

First of all, i named my noxfile `nox.py` which caused a name collision when trying to import `nox`/`poetry-nox`.

With that fixed, I still can't pick up any packages if they're installed with pipx. Maybe this makes sense, seems pipx is for installing applications, rather than libraries.

So i'm installing both nox and poetry-nox using pip

```
pip install --user nox
pip install --user nox-poetry
```

```python
import nox
from nox_poetry import session
```

that was failing because `tomlkit` was installed under some `pyenv` path for some reason. removing and reinstalling fixed *that*.

I'm continually reminded why I hate messing about with system-wide python packages.

**Comment by cjolowicz** [comment]
So is this all working for you now? 

> I'm guessing I'll need to install nox-poetry in both the nox virtualenv and on the system right? In the former so that nox picks it up, and the latter so my IDE picks it up. And then keep them manually aligned. Is that correct?

Ideally you'd teach your IDE to use the environment where Nox is installed when parsing Noxfiles. Having Nox in multiple locations will only lead to confusion.

**Comment by danieleades** [comment]
Yeah, this is all working now.

Incidentally, is there a command for installing *all* dependencies when running tests, or is it necessary to manually list them?
