### ISSUE TITLE
Automatic matrix expansion for extras

### ISSUE THREAD

**Issue by thedrow** [cjolowicz/nox-poetry#290]
It'd be nice to be able to run a session that is already parameterized to install a selected combination of the package's extras.
That way, we can run the tests for all combinations using a single flag.

**Comment by cjolowicz** [comment]
Can you provide an example of how you'd like this to work?

**Comment by thedrow** [comment]
If my package has two extras and I configure nox-poetry to automatically expand the matrix according to my pyproject.toml using:

```
@poetry_nox.session(expand_extras=True)
def test(session):
  pass
```

The result should be that the following sessions: `test(extra1, extra2)`, `test(extra1)`, `test(extra2)`. would be available.

**Comment by cjolowicz** [comment]
Thanks for providing the example!

So essentially you want this:

```python
@nox.session
@nox.parametrize("extras", list(powerset(extras)))
def test(session, extras):
    ...
```

Here `powerset` is the [itertools recipe], and `extras` are your package extras.

Defining the extras as a constant in your Noxfile may be the most pragmatic
solution. But if you want to load them from pyproject.toml, you can take a look
at [poetry.Config.extras] in this package; it will require a TOML library such
as `tomlkit`. (Please note that this class is not part of nox-poetry's public
API.)

[poetry.Config.extras]: https://github.com/cjolowicz/nox-poetry/blob/master/src/nox_poetry/poetry.py#L35
[itertools recipe]: https://docs.python.org/3/library/itertools.html#itertools-recipes

Unfortunately, providing an interface to the Poetry package configuration is
outside of the scope of this package. By extension, so is providing this kind of
session parametrization. nox-poetry is only concerned with installing Poetry
dependencies in Nox sessions such that the lock file is honored.

Let me know if you have any further questions.
