### ISSUE TITLE
Passing pip Install Parameters

### ISSUE THREAD

**Issue by KyleKing** [cjolowicz/nox-poetry#397]
I need pip to use an *index-url* for an internal repository (hosted with devpi), but it doesn't look like there is a way to pass arguments to pip for the initial install other than any global configuration (`pip config edit`)

The best way would be for `poetry export` to also export pip parameters ([docs](https://pip.pypa.io/en/1.1/requirements.html?highlight=zip#indexes-find-links)) in the requiremts.txt file, but getting that merged would be hard given the [~200 PR backlog](https://github.com/python-poetry/poetry/pull/3466) 😢 

The index URL is listed in *tool.poetry.source* of *pyproject.toml*, so *nox-poetry* could potentially extract it from there, but it might be more flexible to add a *pip_params* argument to *nox_session* instead (like the nox *venv_params* kwarg that exists now)

https://github.com/cjolowicz/nox-poetry/blob/8e0262b4412a965e841dd7cda34aab83b58687ae/src/nox_poetry/sessions.py#L21

Which I think could then be passed to this install step:

https://github.com/cjolowicz/nox-poetry/blob/8e0262b4412a965e841dd7cda34aab83b58687ae/src/nox_poetry/sessions.py#L153

**Comment by cjolowicz** [comment]
Why not provide it in the environment (`PIP_INDEX_URL`)?

**Comment by cjolowicz** [comment]
Also, to my knowledge, Poetry does export `--index-url`. There are a few open issues related to that, so maybe you hit one of these. Either way, I'm not very keen on extending the nox-poetry API to tape around an upstream bug.

**Comment by cjolowicz** [comment]
Can you please check the output of `poetry export` in your project? Are you able to `pip install -r requirements.txt` from it?

I suppose that nox-poetry may want to collect pip options from the exported requirements.txt, and pass them via the command-line. They are not valid in a constraints file, so we need to filter them out.

**Comment by KyleKing** [comment]
Thanks for the quick reply!

You're right, the `poetry export` does include the `index-url`; however, the trusted host argument is missing, so `pip install` wouldn't work out of the box (the internal domain is HTTP)

Having nox-poetry handle the pip arguments would be nice, but I'm generally happy with the global pip config appraoch. That is how our developer computers should be configured. We don't have multiple index-urls, but if needed, the `PIP_INDEX_URL` would be a good workaround

I think this issue can probably be closed as not within nox_poetry scope? Or reopened if you wanted to pursue parsing the pip arguments

**Comment by cjolowicz** [comment]
I've opened #398 for the question of collecting pip options from the exported requirements.
