### ISSUE TITLE
Poetry dependency groups

### ISSUE THREAD

**Issue by wwuck** [cjolowicz/nox-poetry#481]
I can see that an upcoming poetry release has support for "dependency groups".

https://python-poetry.org/docs/master/managing-dependencies/

Will this plugin need any updates to accommodate this?

**Comment by cjolowicz** [comment]
I would hope that dependency groups will make nox-poetry entirely redundant. But I haven't looked at them in detail yet.

**Comment by cjolowicz** [comment]
https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/679 has some initial work that demonstrates how dependency groups could replace nox-poetry.

It looks like Poetry still only supports editable installs for the root package. Also, the noxfile needs to export requirements for safety (a tool for checking dependencies against a database of security vulnerabilities). So there's still some amount of glue code that might be easier to maintain in a PyPI package.
