### ISSUE TITLE
Conflicting dependencies with nbformat

### ISSUE THREAD

**Issue by paw-lu** [cjolowicz/nox-poetry#658]
Full disclosure, I haven't looked too deep into this yet. But I keep getting strange dependency errors when trying to use nbformat as a dependency with nox-poetry.

```txt
ERROR: Cannot install debug-nox-poetry==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    debug-nox-poetry 0.1.0 depends on nbformat<6.0.0 and >=5.1.3
    The user requested (constraint) nbformat==5.2.0
```

No complaints from Poetry itself when creating the lockfile. Also I can pip install the package `python -m pip install .` Similarly it works as expected if I use `nox.session` instead of `nox-poetry.session`.

Minimum reproducible repo here:

https://github.com/paw-lu/debug-nox-poetry

**Comment by cjolowicz** [comment]
Thanks for reporting! Should running `nox` in a clone of that repository reproduce the error? It doesn't for me.

**Comment by paw-lu** [comment]
Actually yes, the repository was _meant_ to be reproducible. 

[Tried it again right now from a fresh clone and recorded it.](https://asciinema.org/a/CCrkLsaU9g1Ja06YNA4MsAs2l)

**Comment by cjolowicz** [comment]
Strange. Can you reproduce it in Docker? Here's a Dockerfile:

```Dockerfile
FROM python
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH /root/.local/bin:$PATH
RUN pip install --user nox nox-poetry
RUN git clone https://github.com/paw-lu/debug-nox-poetry
WORKDIR /debug-nox-poetry
RUN nox
```

**Comment by paw-lu** [comment]
Suddenly, I also can't reproduce on my machine. Running the same commands as seen in the orignal recording results in a success.

Also set up an action on Ubuntu—[which also succeeded](https://github.com/paw-lu/debug-nox-poetry/runs/5519978516?check_suite_focus=true).

I'm going to close for now and then reopen if I can get something more reproducible. Sorry for the noise!
