### ISSUE TITLE
Build format `Enum` not being formatted as expected on Python 3.11 macOS runner

### ISSUE THREAD

**Issue by tasansal** [cjolowicz/nox-poetry#978]
Hi, we have this project https://github.com/TGSAI/mdio-python using `nox-poetry` and hypermodern-python cookie cutter style GitHub actions. 

When we run the actions, the macOS runner fails on tests. It appears to be an Enum parsing issue that is happening here.
https://github.com/cjolowicz/nox-poetry/blob/5772b66ebff8d5a3351a08ed402d3d31e48be5f8/src/nox_poetry/poetry.py#L137-L145

I noticed, `pipx` installs `nox` and `nox-poetry` using Python 3.11. It seems like 3.11 introduced changes to the Enum code as seen [here](https://docs.python.org/3/whatsnew/3.11.html#enum). The relevant ones seem to be: 
* Changed [Enum.__format__()](https://docs.python.org/3/library/enum.html#enum.Enum.__format__) (the default for [format()](https://docs.python.org/3/library/functions.html#format), [str.format()](https://docs.python.org/3/library/stdtypes.html#str.format) and [f-string](https://docs.python.org/3/glossary.html#term-f-string)s) of enums with mixed-in types (e.g. [int](https://docs.python.org/3/library/functions.html#int), [str](https://docs.python.org/3/library/stdtypes.html#str)) to also include the class name in the output, not just the member’s key. This matches the existing behavior of [enum.Enum.__str__()](https://docs.python.org/3/library/enum.html#enum.Enum.__str__), returning e.g. 'AnEnum.MEMBER' for an enum AnEnum(str, Enum) instead of just 'MEMBER'.

Currently `nox-poetry` doesn't support 3.11. I see two ways out of this:
* Preferably we make `nox-poetry` Enum parsing support 3.11 changes, so it won't be an issue when 3.11 support rolls out.
* (On hypermodern python side) Make `pipx` not use the system Python version on GitHub runners, not sure how to do that. Even though `3.10` is installed during the run [here](https://github.com/TGSAI/mdio-python/blob/48c181737fc94bf944ee2048e3ec8437204784f8/.github/workflows/tests.yml#L38-L41), `pipx` seems to prefer whatever system version is available. (Appears to pick 3.8 on ubuntu, 3.9 on windows, and 3.11 on mac). Maybe need to update `PATH`?

This is what it should look like (windows test, 3.9.13):
![image](https://user-images.githubusercontent.com/13684161/204311741-5b0de4e7-4331-48f6-a3bb-790c6ecb69f7.png)

But this is what it does (macOS, 3.11):
![image](https://user-images.githubusercontent.com/13684161/204311909-d1afeba5-4546-45f5-b80b-a15acda6a52c.png)

**Comment by tasansal** [comment]
Nevermind, wasn't using the latest `nox-poetry` in `constraints.txt`. User error.

However, hypermodern python `pipx` using system interpreter may still be an issue?

**Comment by johnthagen** [comment]
For historical purposes, this was a duplicate of

- #941
